/*
 * OpenVMP, 2022
 *
 * Author: Roman Kuzmenko
 * Created: 2022-09-27
 *
 * Licensed under Apache License, Version 2.0.
 */

#ifndef OPENVMP_MICROCONTROLLER_CONFIG_H_INCLUDED
#define OPENVMP_MICROCONTROLLER_CONFIG_H_INCLUDED

#define MICROCONTROLLER_CONFIG_CHAPTER_GPIO "gpio"
#define MICROCONTROLLER_CONFIG_CHAPTER_PUL "pul"
#define MICROCONTROLLER_CONFIG_CHAPTER_PWM "pwm"
#define MICROCONTROLLER_CONFIG_CHAPTER_UART "uart"

namespace remote_microcontroller {}

#endif  // OPENVMP_MICROCONTROLLER_CONFIG_H_INCLUDED
