/*
 * OpenVMP, 2023
 *
 * Author: Roman Kuzmenko
 * Created: 2023-03-28
 *
 * Licensed under Apache License, Version 2.0.
 */

#ifndef OPENVMP_REMOTE_MICROCONTROLLER_SERVICE_HPP_INCLUDED
#define OPENVMP_REMOTE_MICROCONTROLLER_SERVICE_HPP_INCLUDED

#define ADDR_SERVICE_MIN 200
#define ADDR_SERVICE_PULSE 200
#define ADDR_SERVICE_MAX 250

#endif  // OPENVMP_REMOTE_MICROCONTROLLER_SERVICE_HPP_INCLUDED
