# GPIO is the only type of I/O accessories here which may cover more than
# one MCU pin with a single record in this file
gpio:
  - prefix: /gpio
    name: driver_gpio0
    channel: 13
    # This switch module will cover 2 channels starting with 13
    switch_channels: 2

pul:
  - channel: 10
    dir_channel: 11
    prefix: /puldir0
    name: driver_puldir0
    actuator_velocity_min: -3.14
    actuator_velocity_max: 3.14
    ppr: 1200

pwm:
  - type: actuator_position
    name: driver_actuator0
    prefix: /actuator0
    actuator_velocity_min: -3.14
    actuator_velocity_max: 3.14
    pwm_min: 0
    pwm_max: 255
  - type: actuator_position
    name: driver_actuator1
    prefix: /actuator1
    actuator_velocity_min: -3.14
    actuator_velocity_max: 3.14
    pwm_min: 0
    pwm_max: 255
  - type: simple_pwm
    name: driver_actuator2
    prefix: /pwm0
    pwm_min: 0
    pwm_max: 255

uart:
  - prefix: /serial
    name: driver_serial0
