/*
 * OpenVMP, 2023
 *
 * Author: Roman Kuzmenko
 * Created: 2023-04-09
 *
 * Licensed under Apache License, Version 2.0.
 */

#ifndef OPENVMP_REMOTE_MICROCONTROLLER_ARDUINO_MEGA2560_PUL_HPP_INCLUDED
#define OPENVMP_REMOTE_MICROCONTROLLER_ARDUINO_MEGA2560_PUL_HPP_INCLUDED

#define PUL_CHANNELS_NUM 54

#endif  // OPENVMP_REMOTE_MICROCONTROLLER_ARDUINO_MEGA2560_PUL_HPP_INCLUDED