/*
 * OpenVMP, 2023
 *
 * Author: Roman Kuzmenko
 * Created: 2023-03-26
 *
 * Licensed under Apache License, Version 2.0.
 */

#ifndef OPENVMP_REMOTE_MICROCONTROLLER_ARDUINO_UNO_UART_HPP_INCLUDED
#define OPENVMP_REMOTE_MICROCONTROLLER_ARDUINO_UNO_UART_HPP_INCLUDED

#define UART_CHANNELS_NUM 1
#define UART_HW_CHANNELS_NUM 0
#define UART_SW_CHANNELS_NUM 1

#endif  // OPENVMP_REMOTE_MICROCONTROLLER_ARDUINO_UNO_UART_HPP_INCLUDED
